ShooterSubsystem
primo4586/off-Season-2024 pull request #1
Opened 2024-07-11 13:22 UTC by Yair4586

i created the ShooterSubsystem

2024-07-11 20:30 UTC, eilonhuppert requested changes

2024-07-11 20:30 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +    _upMotor = new TalonFX(UPMOTOR_ID, Constants.CAN_BUS_NAME);
שם לא רלוונטי

2024-07-11 20:30 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  }
כנ"ל

2024-07-11 20:30 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
add stop motor func, use motor.stopMotor

2024-07-11 20:33 UTC, eilonhuppert requested changes

2024-07-11 20:33 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  /** using a singleton */
not the right comment

2024-07-11 20:33 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public static ShooterSubsystem instance;
public?

2024-07-11 20:33 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public static ShooterSubsystem getInstance() {
java docs

2024-07-11 20:33 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public ShooterSubsystem() {
public?

2024-07-11 20:41 UTC, eilonhuppert commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public ShooterSubsystem() {
its should be private

2024-07-11 20:44 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +    _upMotor = new TalonFX(UPMOTOR_ID, Constants.CAN_BUS_NAME);
v

2024-07-11 20:44 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  }
v

2024-07-11 20:44 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
v

2024-07-11 20:46 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public static ShooterSubsystem instance;
v

2024-07-11 20:48 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public static ShooterSubsystem getInstance() {
v

2024-07-11 20:51 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public ShooterSubsystem() {
v

2024-07-11 21:22 UTC, ori-coval commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  public static ShooterSubsystem getInstance() {
> java docs

its an imp of a singleton dfuck you mean java docs

2024-07-11 21:28 UTC, ori-coval requested changes

2024-07-11 21:28 UTC, ori-coval commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private double targetSpeed = 0;
`targetSpeed` not needed

2024-07-11 21:28 UTC, ori-coval commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +      down_Motor.set(speed);
use motion magic velocity

2024-07-11 21:28 UTC, ori-coval commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        && Math.abs(down_Motor.getVelocity().getValue() - targetSpeed) < MINIMUM_ERROR;
after adding the motion magic velocity do `m_mmReqest.Velocity` instead of using `targetSpeed`

2024-07-12 07:38 UTC, eilonhuppert approved these changes

2024-07-15 15:37 UTC, eilonhuppert requested changes

2024-07-15 15:37 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private void configs(){}
now add configs

2024-07-15 15:37 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +      up_Motor.set(speed);
use mm

2024-07-15 15:37 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterConstants.java
add a constant of base speed and far speed

2024-07-16 20:07 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +      up_Motor.set(speed);
v

2024-07-16 20:07 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private void configs(){}
v

2024-07-16 20:14 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterConstants.java
v

2024-07-16 20:28 UTC, eilonhuppert requested changes

2024-07-16 20:28 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        upConfigs.CurrentLimits.SupplyCurrentLimit = 40;
40? you mean constant?

2024-07-16 20:28 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private MotionMagicVelocityVoltage mm = new MotionMagicVelocityVoltage(0,MOTION_MAGIC_ACCELERATION,true,0.0,0,false,false,false);
תעשה את זה static final וגם וצריך שזה יהיה motion magic FOC

2024-07-16 20:28 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        StatusCode status = StatusCode.StatusCodeNotInitialized;
צריך output של אם זה לא עולה לבקר שתגיד שבמערכת הזאתי הבעיה

2024-07-16 20:40 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        upConfigs.CurrentLimits.SupplyCurrentLimit = 40;
v

2024-07-16 20:49 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        StatusCode status = StatusCode.StatusCodeNotInitialized;
v

2024-07-16 20:49 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private MotionMagicVelocityVoltage mm = new MotionMagicVelocityVoltage(0,MOTION_MAGIC_ACCELERATION,true,0.0,0,false,false,false);
v

2024-07-16 20:49 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +        && Math.abs(down_Motor.getVelocity().getValue() - targetSpeed) < MINIMUM_ERROR;
v

2024-07-16 20:49 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +      down_Motor.set(speed);
v

2024-07-16 20:49 UTC, Yair4586 commented on Off-Season Robot Code/src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
> +  private double targetSpeed = 0;
v

2024-07-21 08:27 UTC, eilonhuppert requested changes

2024-07-21 08:27 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
add a shot from base and a shot from far with 50 RPM and 60RPM and then we done

2024-07-21 10:57 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
because it does not include the arm i think you ment the shot from base is at 50 and shot from far is 60
if i am wrong correct me bc they i'll have 4 commands that bassically do the same thing but 2 use 50 RPM and 2 use 60RPM

2024-07-21 11:01 UTC, Yair4586 commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
i chose to add only 2 command with 1 is shootFromBase and uses 50 RPM and the other is shootFromFar and uses 60RPM

2024-07-21 11:52 UTC, Yair4586 commented
javadocs*

2024-07-21 19:20 UTC, eilonhuppert commented on src/main/java/frc/robot/subsystems/Shooter/ShooterSubsystem.java
Well done you ware correct

2024-07-21 19:20 UTC, merged